import { z } from 'zod';

export const calendarEventOutputSchema = z.object({
  id: z.string().min(1),
  workspace_id: z.string().optional(),
  title: z.string(),
  description: z.string().nullable().optional(),
  start_time: z.string().optional(),
  end_time: z.string().optional(),
  all_day: z.boolean().optional(),
  location: z.string().nullable().optional(),
  meeting_url: z.string().nullable().optional(),
  room_id: z.string().nullable().optional(),
  category_id: z.string().nullable().optional(),
  color: z.string().nullable().optional(),
  organizer_id: z.string().nullable().optional(),
  status: z.string(),
  visibility: z.string().optional(),
  priority: z.string().optional(),
  is_recurring: z.boolean().optional(),
  recurrence_rule: z.record(z.unknown()).nullable().optional(),
  attendees: z.array(z.unknown()).optional(),
  reminders: z.array(z.unknown()).optional(),
  attachments: z.record(z.unknown()).optional(),
  drive_attachment: z.array(z.unknown()).optional(),
  is_occurrence: z.boolean().optional(),
  parent_event_id: z.string().nullable().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
}).strip();

export const upcomingEventsOutputSchema = z.object({
  events: z.array(calendarEventOutputSchema),
});

export const createEventInputShape = {
  title: z.string().min(1).describe('Event title.'),
  start_time: z.string().describe('Event start time in ISO 8601 format.'),
  end_time: z.string().describe('Event end time in ISO 8601 format.'),
  description: z.string().optional().describe('Event description.'),
  all_day: z.boolean().optional().describe('Whether this is an all-day event.'),
  location: z.string().optional().describe('Event location.'),
  room_id: z.string().uuid().optional().describe('Meeting room ID.'),
  category_id: z.string().uuid().optional().describe('Event category ID.'),
  attendees: z.array(z.string()).optional().describe('List of attendee email addresses.'),
  meeting_url: z.string().optional().describe('Meeting URL (Zoom, Teams, etc.).'),
  visibility: z.enum(['private', 'public', 'internal']).optional().describe('Event visibility.'),
  priority: z.enum(['low', 'normal', 'high', 'urgent']).optional().describe('Event priority.'),
  status: z.enum(['confirmed', 'tentative', 'cancelled']).optional().describe('Event status.'),
  is_recurring: z.boolean().optional().describe('Whether this is a recurring event.'),
  recurrence_rule: z.object({
    frequency: z.string(),
    interval: z.number().int().positive().optional(),
    daysOfWeek: z.array(z.string()).optional(),
    byWeekDay: z.array(z.number().int()).optional(),
    endDate: z.string().optional(),
    until: z.string().optional(),
    occurrences: z.number().int().positive().optional(),
  }).optional().describe('Recurrence rule for recurring events.'),
  reminders: z.array(z.number().int().nonnegative()).optional().describe('Reminder settings in minutes before event.'),
  attachments: z.object({
    file_attachment: z.array(z.string().uuid()).optional(),
    note_attachment: z.array(z.string().uuid()).optional(),
    event_attachment: z.array(z.string().uuid()).optional(),
    drive_attachment: z.array(z.object({
      id: z.string().min(1),
      title: z.string().min(1),
      driveFileUrl: z.string().optional(),
      driveThumbnailUrl: z.string().optional(),
      driveMimeType: z.string().optional(),
      driveFileSize: z.number().optional(),
    })).optional(),
  }).optional().describe('Unified attachments object.'),
  description_file_ids: z.array(z.string().uuid()).optional().describe('File IDs embedded in description content.'),
};
