/**
 * Social Media Integrations
 */

const socialMediaIntegrations = [
  {
    slug: 'twitter',
    name: 'Twitter/X',
    description: 'Connect Twitter/X for social media management.',
    category: 'SOCIAL_MEDIA',
    provider: 'X Corp',
    logoUrl: 'https://abs.twimg.com/favicons/twitter.3.ico',
    website: 'https://twitter.com',
    documentationUrl: 'https://developer.twitter.com/en/docs',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://twitter.com/i/oauth2/authorize',
      tokenUrl: 'https://api.twitter.com/2/oauth2/token',
      revokeUrl: 'https://api.twitter.com/2/oauth2/revoke',
      scopes: ['tweet.read', 'tweet.write', 'users.read', 'offline.access'],
      clientIdEnvKey: 'TWITTER_CLIENT_ID',
      clientSecretEnvKey: 'TWITTER_CLIENT_SECRET',
      usePKCE: true
    },
    apiBaseUrl: 'https://api.twitter.com/2',
    capabilities: ['read_tweets', 'post_tweets', 'read_mentions', 'read_followers'],
    features: ['Tweet posting', 'Timeline access', 'Analytics', 'Direct messages'],
    pricingType: 'freemium',
    isVerified: true,
    isFeatured: true
  },
  {
    slug: 'linkedin',
    name: 'LinkedIn',
    description: 'Connect LinkedIn for professional networking.',
    category: 'SOCIAL_MEDIA',
    provider: 'Microsoft',
    logoUrl: 'https://static.licdn.com/sc/h/al2o9zrvru7aqj8e1x2rzsrca',
    website: 'https://linkedin.com',
    documentationUrl: 'https://learn.microsoft.com/en-us/linkedin/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://www.linkedin.com/oauth/v2/authorization',
      tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
      userInfoUrl: 'https://api.linkedin.com/v2/userinfo',
      scopes: ['openid', 'profile', 'email', 'w_member_social'],
      clientIdEnvKey: 'LINKEDIN_CLIENT_ID',
      clientSecretEnvKey: 'LINKEDIN_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://api.linkedin.com/v2',
    capabilities: ['read_profile', 'post_updates', 'read_connections', 'manage_company'],
    features: ['Profile access', 'Post sharing', 'Company pages', 'Analytics'],
    pricingType: 'freemium',
    isVerified: true,
    isFeatured: true
  },
  {
    slug: 'facebook',
    name: 'Facebook',
    description: 'Connect Facebook for social media management.',
    category: 'SOCIAL_MEDIA',
    provider: 'Meta',
    logoUrl: 'https://static.xx.fbcdn.net/rsrc.php/yD/r/d4ZIVX-5C-b.ico',
    website: 'https://facebook.com',
    documentationUrl: 'https://developers.facebook.com/docs/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://www.facebook.com/v18.0/dialog/oauth',
      tokenUrl: 'https://graph.facebook.com/v18.0/oauth/access_token',
      userInfoUrl: 'https://graph.facebook.com/v18.0/me',
      scopes: ['public_profile', 'email', 'pages_show_list', 'pages_read_engagement'],
      clientIdEnvKey: 'FACEBOOK_CLIENT_ID',
      clientSecretEnvKey: 'FACEBOOK_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://graph.facebook.com/v18.0',
    capabilities: ['read_pages', 'post_content', 'read_insights', 'manage_ads'],
    features: ['Page management', 'Post scheduling', 'Insights', 'Ad management'],
    pricingType: 'free',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'instagram',
    name: 'Instagram',
    description: 'Connect Instagram for visual content management.',
    category: 'SOCIAL_MEDIA',
    provider: 'Meta',
    logoUrl: 'https://www.instagram.com/favicon.ico',
    website: 'https://instagram.com',
    documentationUrl: 'https://developers.facebook.com/docs/instagram-api',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://api.instagram.com/oauth/authorize',
      tokenUrl: 'https://api.instagram.com/oauth/access_token',
      scopes: ['user_profile', 'user_media'],
      clientIdEnvKey: 'INSTAGRAM_CLIENT_ID',
      clientSecretEnvKey: 'INSTAGRAM_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://graph.instagram.com',
    capabilities: ['read_media', 'post_content', 'read_insights', 'manage_comments'],
    features: ['Media posting', 'Story insights', 'Comment management', 'Hashtag research'],
    pricingType: 'free',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'tiktok',
    name: 'TikTok',
    description: 'Connect TikTok for short-form video content.',
    category: 'SOCIAL_MEDIA',
    provider: 'ByteDance',
    logoUrl: 'https://www.tiktok.com/favicon.ico',
    website: 'https://tiktok.com',
    documentationUrl: 'https://developers.tiktok.com/doc/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://www.tiktok.com/v2/auth/authorize/',
      tokenUrl: 'https://open.tiktokapis.com/v2/oauth/token/',
      revokeUrl: 'https://open.tiktokapis.com/v2/oauth/revoke/',
      scopes: ['user.info.basic', 'video.list', 'video.upload'],
      clientIdEnvKey: 'TIKTOK_CLIENT_ID',
      clientSecretEnvKey: 'TIKTOK_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://open.tiktokapis.com/v2',
    capabilities: ['read_videos', 'upload_videos', 'read_profile', 'read_analytics'],
    features: ['Video posting', 'Analytics', 'Creator tools', 'Sound library'],
    pricingType: 'free',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'pinterest',
    name: 'Pinterest',
    description: 'Connect Pinterest for visual discovery.',
    category: 'SOCIAL_MEDIA',
    provider: 'Pinterest',
    logoUrl: 'https://www.pinterest.com/favicon.ico',
    website: 'https://pinterest.com',
    documentationUrl: 'https://developers.pinterest.com/docs/api/v5/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://www.pinterest.com/oauth/',
      tokenUrl: 'https://api.pinterest.com/v5/oauth/token',
      scopes: ['boards:read', 'boards:write', 'pins:read', 'pins:write', 'user_accounts:read'],
      clientIdEnvKey: 'PINTEREST_CLIENT_ID',
      clientSecretEnvKey: 'PINTEREST_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://api.pinterest.com/v5',
    capabilities: ['read_pins', 'create_pins', 'manage_boards', 'read_analytics'],
    features: ['Pin creation', 'Board management', 'Rich pins', 'Analytics'],
    pricingType: 'free',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'youtube',
    name: 'YouTube',
    description: 'Connect YouTube for video content management.',
    category: 'SOCIAL_MEDIA',
    provider: 'Google',
    logoUrl: 'https://www.youtube.com/favicon.ico',
    website: 'https://youtube.com',
    documentationUrl: 'https://developers.google.com/youtube/v3',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      userInfoUrl: 'https://www.googleapis.com/oauth2/v2/userinfo',
      scopes: ['youtube.readonly', 'youtube.upload', 'youtube.force-ssl'],
      scopePrefix: 'https://www.googleapis.com/auth/',
      clientIdEnvKey: 'GOOGLE_OAUTH_CLIENT_ID',
      clientSecretEnvKey: 'GOOGLE_OAUTH_CLIENT_SECRET',
      extraAuthParams: { access_type: 'offline', prompt: 'consent' }
    },
    apiBaseUrl: 'https://www.googleapis.com/youtube/v3',
    capabilities: ['read_videos', 'upload_videos', 'manage_playlists', 'read_analytics'],
    features: ['Video upload', 'Playlist management', 'Analytics', 'Live streaming'],
    pricingType: 'free',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'reddit',
    name: 'Reddit',
    description: 'Connect Reddit for community engagement.',
    category: 'SOCIAL_MEDIA',
    provider: 'Reddit',
    logoUrl: 'https://www.reddit.com/favicon.ico',
    website: 'https://reddit.com',
    documentationUrl: 'https://www.reddit.com/dev/api/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://www.reddit.com/api/v1/authorize',
      tokenUrl: 'https://www.reddit.com/api/v1/access_token',
      revokeUrl: 'https://www.reddit.com/api/v1/revoke_token',
      scopes: ['identity', 'read', 'submit', 'subscribe'],
      clientIdEnvKey: 'REDDIT_CLIENT_ID',
      clientSecretEnvKey: 'REDDIT_CLIENT_SECRET',
      extraAuthParams: { duration: 'permanent' }
    },
    apiBaseUrl: 'https://oauth.reddit.com',
    capabilities: ['read_posts', 'submit_posts', 'read_comments', 'manage_subreddits'],
    features: ['Post submission', 'Comment tracking', 'Subreddit monitoring', 'Karma tracking'],
    pricingType: 'free',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'snapchat',
    name: 'Snapchat',
    description: 'Connect Snapchat for ephemeral content.',
    category: 'SOCIAL_MEDIA',
    provider: 'Snap',
    logoUrl: 'https://www.snapchat.com/favicon.ico',
    website: 'https://snapchat.com',
    documentationUrl: 'https://developers.snap.com/api/marketing-api/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://accounts.snapchat.com/oauth2/auth',
      tokenUrl: 'https://accounts.snapchat.com/oauth2/token',
      scopes: ['snapchat-marketing-api'],
      clientIdEnvKey: 'SNAPCHAT_CLIENT_ID',
      clientSecretEnvKey: 'SNAPCHAT_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://adsapi.snapchat.com/v1',
    capabilities: ['manage_ads', 'read_insights', 'create_audiences', 'manage_creatives'],
    features: ['Ad management', 'Audience targeting', 'Snap pixel', 'Campaign analytics'],
    pricingType: 'paid',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'buffer',
    name: 'Buffer',
    description: 'Connect Buffer for social media scheduling.',
    category: 'SOCIAL_MEDIA',
    provider: 'Buffer',
    logoUrl: 'https://buffer.com/favicon.ico',
    website: 'https://buffer.com',
    documentationUrl: 'https://buffer.com/developers/api',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://bufferapp.com/oauth2/authorize',
      tokenUrl: 'https://api.bufferapp.com/1/oauth2/token.json',
      scopes: [],
      clientIdEnvKey: 'BUFFER_CLIENT_ID',
      clientSecretEnvKey: 'BUFFER_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://api.bufferapp.com/1',
    capabilities: ['read_profiles', 'create_updates', 'read_analytics', 'manage_schedules'],
    features: ['Post scheduling', 'Analytics', 'Team collaboration', 'Content calendar'],
    pricingType: 'freemium',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'hootsuite',
    name: 'Hootsuite',
    description: 'Connect Hootsuite for social media management.',
    category: 'SOCIAL_MEDIA',
    provider: 'Hootsuite',
    logoUrl: 'https://hootsuite.com/favicon.ico',
    website: 'https://hootsuite.com',
    documentationUrl: 'https://developer.hootsuite.com/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://platform.hootsuite.com/oauth2/auth',
      tokenUrl: 'https://platform.hootsuite.com/oauth2/token',
      scopes: ['offline'],
      clientIdEnvKey: 'HOOTSUITE_CLIENT_ID',
      clientSecretEnvKey: 'HOOTSUITE_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://platform.hootsuite.com/v1',
    capabilities: ['read_messages', 'schedule_posts', 'read_analytics', 'manage_teams'],
    features: ['Multi-platform posting', 'Inbox management', 'Analytics', 'Team workflows'],
    pricingType: 'paid',
    isVerified: true,
    isFeatured: false
  },
  {
    slug: 'sprout-social',
    name: 'Sprout Social',
    description: 'Connect Sprout Social for enterprise social management.',
    category: 'SOCIAL_MEDIA',
    provider: 'Sprout Social',
    logoUrl: 'https://sproutsocial.com/favicon.ico',
    website: 'https://sproutsocial.com',
    documentationUrl: 'https://developers.sproutsocial.com/',
    authType: 'oauth2',
    authConfig: {
      authorizationUrl: 'https://api.sproutsocial.com/oauth/authorize',
      tokenUrl: 'https://api.sproutsocial.com/oauth/access_token',
      scopes: [],
      clientIdEnvKey: 'SPROUT_SOCIAL_CLIENT_ID',
      clientSecretEnvKey: 'SPROUT_SOCIAL_CLIENT_SECRET'
    },
    apiBaseUrl: 'https://api.sproutsocial.com/v1',
    capabilities: ['read_messages', 'schedule_posts', 'read_analytics', 'manage_listening'],
    features: ['Publishing', 'Engagement', 'Analytics', 'Social listening'],
    pricingType: 'paid',
    isVerified: true,
    isFeatured: false
  }
];

module.exports = { socialMediaIntegrations };
